version: '3'

services:
  mongo:
    image: mongo:5.0.12
    restart: always
    ports:
      - "27020:27017"  # host:container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ht
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
